use libc::c_int;

/// Struct that represents static data on C side.
/// It stores various ids that are generated by Wireshark
/// to identify items inside dissected Tezos frame.
#[repr(C)]
pub struct T3zosDissectorInfo {
    pub hf_payload_len: c_int,
    pub hf_packet_counter: c_int,
    pub hf_connection_msg: c_int,
    pub hf_decrypted_msg: c_int,
    pub hf_error: c_int,

    pub hf_debug: c_int,
}
